import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import WavesBackground from "@/components/WavesBackground";
import { AuthProvider } from "@/context/AuthContext";

const height: number = 4;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-[100vh]`}
      >
        <AuthProvider>
          {/* Vanta Waves Background */}
          <WavesBackground
            waveColor={0x1e40af}
            backgroundColor={0x2563eb}
            shininess={60}
            waveHeight={40}
            waveSpeed={1}
            scale={1.3}
            scaleMobile={1.3}
            zoom={0.6}
          />
          <div className="h-full w-full flex flex-col">
            <Navbar height={height} />
            <main style={{ height: `calc(100vh - ${height}rem)` }}>
              {children}
            </main>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
